version: '3.4'

services:
  pitwall.server.api:
    container_name: pitwall.server.api
    image: ${DOCKER_REGISTRY-}pitwallserverapi
    ports:
     - 3500:8080
     - 3501:8081
    build:
      context: .
      dockerfile: Pitwall.Server.Api/Dockerfile
    depends_on:
      pitwall.server.db:
        condition: service_healthy
      pitwall.server.cache:
        condition: service_healthy
  pitwall.server.db:
   container_name: pitwall.server.db
   ports:
    - "1433:1433"
   environment:
    ACCEPT_EULA: "Y"
    SA_PASSWORD: VPW_dev_pw!
   image: mcr.microsoft.com/mssql/server:2022-latest
   restart: always
   healthcheck:
    test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P VPW_dev_pw! -Q 'SELECT 1' || exit 1"]
    interval: 10s
    retries: 10
    start_period: 10s
    timeout: 3s
  pitwall.server.cache:
   container_name: pitwall.server.cache
   image: redis:latest
   restart: always
   ports:
    - "6379-6379"
   healthcheck:
    test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
    interval: 1s
    timeout: 3s
    retries: 5
