import type { Metadata } from 'next'
import { Providers } from '@/lib/providers'
import Script from 'next/script';
import { Inter } from 'next/font/google'
import './globals.css'
import '../../node_modules/react-grid-layout/css/styles.css'
import '../../node_modules/react-resizable/css/styles.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <head>
          <script src='/js/RivalTracker.1.0.js'></script>
          <script src='/js/TrackPaths.min.js'></script>
          <script src='/js/RivalTrackerPaths.1.0.js'></script>
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  )
}
